/**
 * Market Maker Types
 *
 * Core types for the market making system.
 */

/** Order side (YES or NO contract) */
export type Side = "yes" | "no";

/** Order action (buy or sell) */
export type Action = "buy" | "sell";

/** Order status in lifecycle */
export type OrderStatus =
  | "pending"
  | "open"
  | "partial"
  | "filled"
  | "cancelled"
  | "failed";

/**
 * A managed order tracked by the OrderManager
 */
export interface ManagedOrder {
  /** Kalshi order ID (assigned after placement) */
  id?: string;
  /** Client-generated order ID for tracking */
  clientOrderId: string;
  /** Market ticker */
  ticker: string;
  /** YES or NO */
  side: Side;
  /** Buy or sell */
  action: Action;
  /** Price in cents (1-99) */
  price: number;
  /** Number of contracts */
  count: number;
  /** Current order status */
  status: OrderStatus;
  /** When the order was created */
  createdAt: Date;
  /** Number of contracts filled */
  filledCount: number;
  /** Average fill price (cents) */
  avgFillPrice?: number;
}

/**
 * Quote generated by a strategy
 */
export interface Quote {
  ticker: string;
  side: Side;
  /** Bid price in cents */
  bidPrice: number;
  /** Bid size in contracts */
  bidSize: number;
  /** Ask price in cents */
  askPrice: number;
  /** Ask size in contracts */
  askSize: number;
}

/**
 * Position in a single market
 */
export interface Position {
  ticker: string;
  /** Number of YES contracts held (positive = long, negative = short) */
  yesContracts: number;
  /** Number of NO contracts held (positive = long, negative = short) */
  noContracts: number;
  /** Net exposure: yesContracts - noContracts */
  netExposure: number;
  /** Total cost basis in cents (legacy - sum of yesCostBasis + noCostBasis) */
  costBasis: number;
  /** Cost basis for YES contracts in cents */
  yesCostBasis: number;
  /** Cost basis for NO contracts in cents */
  noCostBasis: number;
  /** Unrealized PnL in cents */
  unrealizedPnL: number;
}

/**
 * Risk limits configuration
 */
export interface RiskLimits {
  /** Max contracts per market (absolute value) */
  maxPositionPerMarket: number;
  /** Max total contracts across all markets */
  maxTotalExposure: number;
  /** Max daily loss in cents before halting */
  maxDailyLoss: number;
  /** Max contracts per single order */
  maxOrderSize: number;
  /** Minimum spread to quote (cents) */
  minSpread: number;
}

/**
 * Result of a risk check
 */
export interface RiskCheckResult {
  /** Whether the action is allowed */
  allowed: boolean;
  /** Reason if not allowed */
  reason?: string;
}

/**
 * Fill event from Kalshi
 */
export interface Fill {
  /** Order ID that was filled */
  orderId: string;
  /** Market ticker */
  ticker: string;
  /** YES or NO */
  side: Side;
  /** Buy or sell */
  action: Action;
  /** Number of contracts filled */
  count: number;
  /** Fill price in cents */
  price: number;
  /** Timestamp */
  timestamp: Date;
}

/**
 * PnL summary
 */
export interface PnLSummary {
  /** Realized PnL today (cents) */
  realizedToday: number;
  /** Unrealized PnL (cents) */
  unrealized: number;
  /** Total PnL (cents) */
  total: number;
  /** Number of fills today */
  fillsToday: number;
  /** Total volume traded today (contracts) */
  volumeToday: number;
}

